// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMAi6NqvKetQpnQmPbtt-VGBycGoU4ehM',
    appId: '1:996194713374:web:9e678b5736b99587ced30f',
    messagingSenderId: '996194713374',
    projectId: 'catalogo-marvel-af56b',
    authDomain: 'catalogo-marvel-af56b.firebaseapp.com',
    storageBucket: 'catalogo-marvel-af56b.appspot.com',
    measurementId: 'G-SS9GVXK0EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHo0s13W106nnQ1WaFPDYrA9yGXomweBw',
    appId: '1:996194713374:android:bb712c585a402ceaced30f',
    messagingSenderId: '996194713374',
    projectId: 'catalogo-marvel-af56b',
    storageBucket: 'catalogo-marvel-af56b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlGyMllnzDZNR8bjKRpgTfinpUp46hAtM',
    appId: '1:996194713374:ios:66da23d200dd49a2ced30f',
    messagingSenderId: '996194713374',
    projectId: 'catalogo-marvel-af56b',
    storageBucket: 'catalogo-marvel-af56b.appspot.com',
    iosBundleId: 'mkb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlGyMllnzDZNR8bjKRpgTfinpUp46hAtM',
    appId: '1:996194713374:ios:f53ae7af70676adbced30f',
    messagingSenderId: '996194713374',
    projectId: 'catalogo-marvel-af56b',
    storageBucket: 'catalogo-marvel-af56b.appspot.com',
    iosBundleId: 'm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMAi6NqvKetQpnQmPbtt-VGBycGoU4ehM',
    appId: '1:996194713374:web:788e60c0753086b0ced30f',
    messagingSenderId: '996194713374',
    projectId: 'catalogo-marvel-af56b',
    authDomain: 'catalogo-marvel-af56b.firebaseapp.com',
    storageBucket: 'catalogo-marvel-af56b.appspot.com',
    measurementId: 'G-B13W49LSY3',
  );
}
